Update xcode project and add xcode to nativeBuild

diff --git a/build/bin/nativeBuild b/build/bin/nativeBuild
--- a/build/bin/nativeBuild
+++ b/build/bin/nativeBuild
@@ -16,33 +16,69 @@ log() {
     printf "%12s %s\n" $tag "$*"
 }
 
-if [ -x "${VS}" ] ; then
-    if [ ! -f src/include/buildConfig.save ] ; then
-        mv src/include/buildConfig.h src/include/buildConfig.save
-    fi
-    cp src/include/master/buildConfig.h src/include
-
-    log "[Test]" "Building ${BLD_PRODUCT}-dynamic VS project"
-    rm -fr projects/WIN/*/Win32
-    "${VS}" projects/WIN/${BLD_PRODUCT}-dynamic/*.sln /clean
-    "${VS}" projects/WIN/${BLD_PRODUCT}-dynamic/*.sln /build
-
-    if [ -f src/include/buildConfig.save ] ; then
-        mv src/include/buildConfig.save src/include/buildConfig.h
-    fi
-    rm -fr projects/WIN/*/Win32
-
-    echo TESTING TARGETS
-
-    status=0
-    for f in ejs ejsc ejsmod ejssql http
-    do
-        if [ !-x $BLD_BIN_DIR/${f}${BLD_EXE} ] ; then
-            echo Missing target $BLD_BIN_DIR/${f}${BLD_EXE} >&2
-            status=255
+winBuild() {
+    local status=0
+    if [ -x "${VS}" ] ; then
+        if [ ! -f src/include/buildConfig.save ] ; then
+            mv src/include/buildConfig.h src/include/buildConfig.save
         fi
-    done
+        cp src/include/master/buildConfig.h src/include
 
-    echo STATUS $status
-    return $status
-fi
+        log "[Test]" "Building ${BLD_PRODUCT}-dynamic VS project"
+        rm -fr projects/WIN/*/Win32
+        "${VS}" projects/WIN/${BLD_PRODUCT}-dynamic/*.sln /clean
+        if [ $? != 0 ] ; then
+            echo Failed to clean: "${VS}" projects/WIN/${BLD_PRODUCT}-dynamic/*.sln /clean
+        fi
+        "${VS}" projects/WIN/${BLD_PRODUCT}-dynamic/*.sln /build
+        if [ $? != 0 ] ; then
+            echo Failed to build: "${VS}" projects/WIN/${BLD_PRODUCT}-dynamic/*.sln /build
+        fi
+
+        if [ -f src/include/buildConfig.save ] ; then
+            mv src/include/buildConfig.save src/include/buildConfig.h
+        fi
+        rm -fr projects/WIN/*/Win32
+
+        echo TESTING TARGETS
+
+        for f in ejs ejsc ejsmod ejssql http
+        do
+            if [ !-x $BLD_BIN_DIR/${f}${BLD_EXE} ] ; then
+                echo Missing target $BLD_BIN_DIR/${f}${BLD_EXE} >&2
+                status=255
+            fi
+        done
+        echo STATUS $status
+        exit $status
+    fi
+}
+
+macBuild() {
+    if which xcodebuild >/dev/null 2>&1 ; then
+        if [ "$BLD_TYPE" = "DEBUG" ] ; then
+            config=Debug
+        else
+            config=Release
+        fi
+#        xcodebuild -project projects/MACOSX/ejs-all/ejs-all.xcodeproj -configuration $config clean
+#        if [ $? != 0 ] ; then
+#            echo Failed to clean: xcodebuild -project projects/MACOSX/ejs-all/ejs-all.xcodeproj -configuration $config clean
+#        fi
+        xcodebuild -project projects/MACOSX/ejs-all/ejs-all.xcodeproj -configuration $config
+        if [ $? != 0 ] ; then
+            echo Failed to build: xcodebuild -project projects/MACOSX/ejs-all/ejs-all.xcodeproj -configuration $config
+        fi
+    fi
+}
+
+case $BLD_OS in
+WIN)
+    winBuild
+    ;;
+MACOSX)
+    macBuild
+    ;;
+*)
+    ;;
+esac
